### ISSUE TITLE
not compiling with teensy 3.2

### ISSUE THREAD

**Issue by balamsoto** [simondlevy/MB1242#2]
compiles fine with teensy Lc and 3.6
with 3.2 get this error:

/Arduino.app/Contents/Java/hardware/teensy/avr/libraries/Wire/WireKinetis.h:219:16: note: previous declaration as 'TwoWire Wire1'
 extern TwoWire Wire1;

error: no matching function for call to 'TwoWire::begin(i2c_mode, int, i2c_pins, i2c_pullup, int)'
   Wire.begin(I2C_MASTER, 0x00, I2C_PINS_18_19, I2C_PULLUP_INT, 400000);
                                                                      ^
In file included from /Applications/Arduino.app/Contents/Java/hardware/teensy/avr/libraries/Wire/Wire.h:26:0,
                 from /Users/balam/Documents/INTER-SOFTWARE/Arduino/libraries/Skywriter/skywriter.h:1,
                 from /var/folders/qc/b0k6l43j12126b25br1p92nw0000gn/T/arduino_modified_sketch_948625/Beta-1Skywrite-midi-sonar.ino:3:
/Applications/Arduino.app/Contents/Java/hardware/teensy/avr/libraries/Wire/WireKinetis.h:97:7: note: candidate: void TwoWire::begin()
  void begin();
       ^
/Applications/Arduino.app/Contents/Java/hardware/teensy/avr/libraries/Wire/WireKinetis.h:97:7: note:   candidate expects 0 arguments, 5 provided
/Applications/Arduino.app/Contents/Java/hardware/teensy/avr/libraries/Wire/WireKinetis.h:98:7: note: candidate: void TwoWire::begin(uint8_t)
  void begin(uint8_t address);
       ^
/Applications/Arduino.app/Contents/Java/hardware/teensy/avr/libraries/Wire/WireKinetis.h:98:7: note:   candidate expects 1 argument, 5 provided
/Applications/Arduino.app/Contents/Java/hardware/teensy/avr/libraries/Wire/WireKinetis.h:99:7: note: candidate: void TwoWire::begin(int)
  void begin(int address) {
       ^
/Applications/Arduino.app/Contents/Java/hardware/teensy/avr/libraries/Wire/WireKinetis.h:99:7: note:   candidate expects 1 argument, 5 provided
Error compiling for board Teensy 3.2 / 3.1.
